# Generated by Django 5.2.6 on 2025-09-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management_system_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
